from typing import Literal, Optional, List
from typing_extensions import TypedDict

# =========================================================
# Shared State Definition for DevOps Incident Response Agent
# =========================================================
class RouterState(TypedDict):
    """
    Shared state for the DevOps Incident Response Agent.

    This state flows through:
    1. Router (LLM decides domain)
    2. Specialist agent (k8s/db/network/cicd)
    3. Summarizer agent (final response)

    Each node updates only relevant fields.
    """

    # -----------------------------
    # Input
    # -----------------------------
    incident: str

    # -----------------------------
    # Routing decision (LLM output)
    # -----------------------------
    route: Optional[
        Literal[
            "kubernetes",
            "database",
            "network",
            "cicd"
        ]
    ]

    # -----------------------------
    # Specialist output (structured)
    # -----------------------------
    diagnosis: Optional[str]

    # Commands generated by specialist agent
    # These can be:
    # - kubectl commands
    # - SQL queries
    # - curl / nslookup / dig
    # - CI/CD CLI commands
    commands: Optional[List[str]]

    # Optional raw logs or evidence (future extension)
    evidence: Optional[List[str]]

    # -----------------------------
    # Final response (LLM summary)
    # -----------------------------
    final_response: Optional[str]